name: IPO GMP Monitor

on:
  schedule:
    - cron: '15 9 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-ipo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Install ChromeDriver
      run: |
        pip install webdriver-manager
    
    - name: Run IPO monitor
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        python ipo_monitor.py
